### ISSUE TITLE
Implementation of missing special pages

### ISSUE THREAD

**Issue by ekspek** [ekspek/ist-thesis#6]
The thesis example is still missing some special pre- and post-main text pages, which I'm still not entirely familiar with the workings of. The full list of special pages is
- Glossary
- Nomenclature
- List of symbols
- Index
- Bibliography

The most notable special page here is the bibliography, which is already included in the thesis example but not in the class file itself.

More important than working on implementing the features above is debating which ones are actually necessary, and within those which ones can be implemented into the class file and which ones are better left to the thesis example alone. This will depend on the difficulty of implementation and usage and should be fully thought through.

**Comment by jomigo96** [comment]
In all cases, the user should be free to use the packages he wants, those shouldn't be enforced by the class. On the other hand, the **style** should match the IST directives, and other than covering every possible package to implement those pages, the solution would be to leave that for the template.
This also makes the class more extensible.

**Comment by ekspek** [comment]
Good point. I'll leave any special pages that have external dependencies (like running `biber` or `makeglossaries`) to the template. Ideally the template could be modular in nature (so every style option can be changed or removed), but that kinda stuff could be developed further down the line (so not really a priority).

I'll leave the issue open until we can get a working template with the pages above defined with examples. I've added the `template` issue label in the meantime.

**Comment by ekspek** [comment]
Most missing extra pages listed have been added. Index will be skipped because of a debatable relevance.
