### ISSUE TITLE
English translation of the documentation

### ISSUE THREAD

**Issue by ekspek** [ekspek/ist-thesis#8]
Although it's a mighty lot to ask, the next step is adding an english translation of the documentation for any foreign students who might need it.

**Comment by joaoestudante** [comment]
I don't mind working on this, if no one has taken the challenge yet.

**Comment by jomigo96** [comment]
Be my guest

**Comment by ekspek** [comment]
Yeah same, use your own words if you want to. Doesn't have to be a carbon copy of the original.

Feel free to ask any questions too.

**Comment by joaoestudante** [comment]
Will do, thanks.

**Comment by ekspek** [comment]
Solved in #14.
